# This file is for custom makefile variable at the project level.
# They are meant to be share by the whole project team.

APPLICATION_NAME := climateset
CONDA_ENVIRONMENT := climateset
PYTHON_VERSION := 3.11
