CMIP6:
  models: ["NorESM2-LM"]
  downloader_kwargs:
    variables: ["tas", "pr"]
    experiments: ["historical","ssp126", "ssp245", "ssp370", "ssp585"]
input4MIPs:
  downloader_kwargs:
      variables: ["CO2", "BC", "SO2", "CH4"]
      experiments: ["historical","ssp126", "ssp245", "ssp370", "ssp585"]
