CMIP6:
  model: "NorESM2-LM"
  variables: ["tas", "pr"]
  experiments: ["historical","ssp126", "ssp245", "ssp370", "ssp585"]
input4MIPs:
  variables: ["CO2", "BC", "SO2", "CH4"]
  experiments: ["historical","ssp126", "ssp245", "ssp370", "ssp585"]
