name: Pre-commit

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Pre-commit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: climateset
          use-mamba: true

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('etc/example-environment-caching.yml') }}-${{ env.CACHE_NUMBER
            }}
        env:
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run:
          mamba env update -n climateset -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install dependencies
        run: |
          make CONDA_TOOL=mamba install

      - name: Run Pre-commit checks
        run: |
          make precommit
